### ISSUE TITLE
ImportError: cannot import name 'Sequence' from 'collections'

### ISSUE THREAD

**Issue by solarmcpanel** [python-openxml/python-docx#1151]
I'm using docx 0.8.10. import does not appear to work with python 3.10+. This is because an attempt is made to  import name 'Sequence' from 'collections' in section.py line 7: in python 3.10+ it should be "from collections.abc import Sequence".

**Comment by valentinoli** [comment]
I solved this by upgrading to `0.8.11`

**Comment by solarmcpanel** [comment]
Thank you for the response 🙏 On 8 Apr 2023 16:11, Valentin Oliver Loftsson ***@***.***> wrote:
I solved this by upgrading to 0.8.11
